### Numpy array from Scratch

In [6]:
import numpy as np 

In [26]:
np_array = np.array([1,2,3,4,5,6])
print(np_array)

matrix = np.array([[1,2,3],
                  [4,5,6]])
tensor = np.array([[[1,2], [3,4]],
                   [[5,6] ,[7,8] ]])
print(tensor)

[1 2 3 4 5 6]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Numpy array vs List

In [12]:
np_array =  np.array([1,2,3])
print("np array is :" , np_array*2) # multipling every element 

lst = [4,5,6]
print("list  is :", lst*2) # double size of list
# comparision b/w array, list 
import time

start = time.time()
arr = np.arange(1000000) *2
print("array creation time is:" , time.time() - start)

start2 = time.time()
list = [i*2 for i  in range(1000000)] 
print("list creation time is:" , time.time() - start2)


np array is : [2 4 6]
list  is : [4, 5, 6, 4, 5, 6]
array creation time is: 0.01074671745300293
list creation time is: 0.12188935279846191


### Creating array from scratch 

In [25]:
zero_array = np.zeros((2,4))
print("three" , zero_array)
ones = np.ones((2,3))
print("three" , ones)
full  = np.full((2,3) ,3)
print("three" , full)
randm = np.random.random((3,3))
print(randm)
sequence = np.arange(1, 13, 2, int)
print(sequence)

three [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
three [[1. 1. 1.]
 [1. 1. 1.]]
three [[3 3 3]
 [3 3 3]]
[[0.29732331 0.53953933 0.4119387 ]
 [0.99127911 0.56637162 0.67456422]
 [0.75489623 0.38400087 0.6326011 ]]
[ 1  3  5  7  9 11]


### Array Properties

In [ ]:
arr = np.array([[1,2,3,4], 
            [5,6,7,8]])

print(" row, colmn", arr.shape)
print(" total element ", arr.size)
print("Dymention ", arr.ndim)
print(" Data type ", arr.dtype)

# transpose a matrix  
t = arr.T
print(t)

 row, colmn (2, 4)
 total element  8
Dymention  2
 Data type  int64
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### Array reshaping and ravel

In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
reshape  = arr.reshape((2,5))
print(reshape)
 
flat = reshape.flatten()
print("flat array is", flat) 
 
raveled = reshape.ravel()
print("raveled array" , raveled) 
print(" reshaped array  ",  reshape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
flat array is [1 2 3 4 5 6 7 8 9 0]
raveled array [1 2 3 4 5 6 7 8 9 0]
 reshaped array   [[1 2 3 4 5]
 [6 7 8 9 0]]
