### Numpy array Operations

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:6])
print(arr[3:6:2])
print(arr[-2]) 

[4 5 6]
[4 6]
6


## Slice in 2D array 

In [36]:
ar = np.array([[1,2,3,4],
[5,6,7,8],
[12,33,44,55]])

print(ar[1,3]) # an element at (1,3) position
print(ar[1]) # 2nd row
print(ar[:,2]) # 3rd colomn 
print(ar[1:3, 2:3])  

8
[5 6 7 8]
[ 3  7 44]
[[ 7]
 [44]]


## Sorting 


In [28]:
arr = np.array([1,2,3,4,5])
print(np.sort(arr))

arr_2d = np.array([[2,3,4],[3,2,1],[0,7,9]])
print("colomn wise sorting ", np.sort(arr_2d, axis=0))


[1 2 3 4 5]
colomn wise sorting  [[0 2 1]
 [2 3 4]
 [3 7 9]]


### filter with mask 

In [22]:
mask = arr % 2 == 0
a = arr[mask]
print(a)
mask = arr > 3
b  = arr[mask]
print(b)

[2 4]
[4 5]


### Fancy Indexing and np.where

In [7]:
number = np.array([2,3,4,5,6,1])
indices = [0,1,3] 
print(number[indices])
# print("without reference" ,number[0,1,3] ) #IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
print("without reference" ,number[([0,1,3])] )  

ind = np.where(number > 4)
print(ind)
print(" from np.where indeces",number[ind])
 

[2 3 5]
without reference [2 3 5]
(array([3, 4]),)
 from np.where indeces [5 6]


In [8]:
condition  = np.where(number > 2, True ,False)
print(condition)

[False  True  True  True  True False]


## Adding  and Removinng 

In [15]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([0,0,7,4,8,9])
print(ar1 + ar2)
print(np.concatenate((ar1,ar2))) 
print(np.delete(ar1, 3))

# Compatibility check 
print("1 nad 2 are comapatible or not :", ar1.shape == ar2.shape) 


[ 1  2 10  8 13 15]
[1 2 3 4 5 6 0 0 7 4 8 9]
[1 2 3 5 6]
1 nad 2 are comapatible or not : True


In [27]:
arr = np.array([[2,3,4],[5,6,7],[8,9,10]])
r = np.array([0,0,0])
print("new array with new row", np.vstack((arr , r))) 
c = np.array([[0],[0],[0]])
print("adding new colomn :", np.hstack((arr, c))) 

print(" After deleting the row " , np.delete(arr , 1, 0))
print(" After deleting the colomn " , np.delete(arr , 1, 1))

new array with new row [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [ 0  0  0]]
adding new colomn : [[ 2  3  4  0]
 [ 5  6  7  0]
 [ 8  9 10  0]]
 After deleting the row  [[ 2  3  4]
 [ 8  9 10]]
 After deleting the colomn  [[ 2  4]
 [ 5  7]
 [ 8 10]]
